#ifndef TEST_TEXTURE_ENUMS_H
#define TEST_TEXTURE_ENUMS_H

enum TextureProperties
{
  TEXTURE_WIDTH     = 64,
  TEXTURE_HEIGHT    = 64,
  TEXTURE_FORMAT    = R8B8G8A8_UNORM,
  TEXTURES_PER_CUBE = 6,
  NUM_CUBES         = 2,
};

#endif /* TEST_TEXTURE_ENUMS_H */
