#ifndef TEST_TEXTURE_ENUMS_H
#define TEST_TEXTURE_ENUMS_H

enum TextureProperties
{
  RTV_TEX_WIDTH  = 64,
  RTV_TEX_HEIGHT = 64,
  RTV_TEX_FORMAT = R8B8G8A8_UNORM,
};

#endif /* TEST_TEXTURE_ENUMS_H */
