#ifndef TEST_TEXTURE_ENUMS_H
#define TEST_TEXTURE_ENUMS_H

enum TextureModes
{
  TEXTURE_MODE_1D = 0,
  TEXTURE_MODE_2D,
  TEXTURE_MODE_3D,
  TEXTURE_MODE_1D_ARRAY,
  TEXTURE_MODE_2D_ARRAY,
  TEXTURE_MODE_CUBE,
  TEXTURE_MODE_CUBE_ARRAY,
  TEXTURE_MODE_MAX
};

enum TextureProperties
{
  TEXTURE_WIDTH     = 64,
  TEXTURE_HEIGHT    = 64,
  TEXTURE_DEPTH     = 8,
  TEXTURE_FORMAT    = R8B8G8A8_UNORM,
  NUM_MIPMAPS       = 2,
  ARRAY_SIZE        = 2,
  TEXTURES_PER_CUBE = 6
};

#endif /* TEST_TEXTURE_ENUMS_H */
